package es.upm.fis2018.gm11_6.core;

import java.util.ArrayList;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : Conversacion.java
//  @ Date : 23/05/2018
//  @ Author :
//
//




public class Conversacion {
	private int idConversacion; 
	private ArrayList<Mensaje> listaMensajes;
	private Usuario receptor;
	private Usuario emisor;
	
	public Conversacion(int idC, Usuario em, Usuario rec) {
		this.idConversacion = idC;
		this.listaMensajes = new ArrayList<Mensaje>();
		this.emisor = em;
		this.receptor = rec;		
	}

	//mostrar mensajes
	public void mostrarMensajes() {
		System.out.println("-----" + this.receptor.getCorreoUPM() + " - " + this.emisor.getCorreoUPM());
		for (int i = 0; i < this.listaMensajes.size(); i++) {
			System.out.println("[" + i + "]" + "(" + this.listaMensajes.get(i).getCreationDate().toString() + ") " + this.listaMensajes.get(i).getEmisor().getNombre().toUpperCase() + ": '" + this.listaMensajes.get(i).getContenido() + "'" );
		}
		System.out.print("---------- FIN DE LA CONVERSACION ----------");
	}
	//anyadir mensajes
	public void anyadirMensaje(String cont, Usuario em) {
		this.listaMensajes.add(new Mensaje(cont,em));
		System.out.println("Mensaje enviado.");
	}
	//borrar mensaje
	public void borrarMensaje(int idM, Usuario em) {
		this.mostrarMensajes();
		if (this.listaMensajes.get(idM).getEmisor().getNombre().equals(em.getNombre())){
			this.listaMensajes.remove(idM);
			System.out.println("Mensaje borrado");
		} else System.out.println("No puedes borrar un mensaje que no es tuyo");
	}
	
	
	
	
	
	// getters and setters
	public int getIdConversacion() {
		return idConversacion;
	}
	public void setIdConversacion(int idConversacion) {
		this.idConversacion = idConversacion;
	}

	public ArrayList<Mensaje> getListaMensajes() {
		return listaMensajes;
	}

	public void setListaMensajes(ArrayList<Mensaje> listaMensajes) {
		this.listaMensajes = listaMensajes;
	}

	public Usuario getReceptor() {
		return receptor;
	}

	public void setReceptor(Usuario receptor) {
		this.receptor = receptor;
	}

	public Usuario getEmisor() {
		return emisor;
	}

	public void setEmisor(Usuario emisor) {
		this.emisor = emisor;
	}
	
}
