package es.upm.fis2018.gm11_6.core;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : Proxy.java
//  @ Date : 23/05/2018
//  @ Author :
//
//




public class Proxy extends Subject {
	public Grupo RealSubject;
}
