package es.upm.fis2018.gm11_6.core;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : UsuarioBasedeDatos.java
//  @ Date : 23/05/2018
//  @ Author : 
//
//




public class UsuarioBasedeDatos {
	private UsuarioBasedeDatos instance;
	
	public void newUsuario() {
	
	}
	
	public void deleteUsuario() {
	
	}
	
	public void selectUsuario() {
	
	}
	
	public UsuarioBasedeDatos instance() {
		return this;
	}

	public UsuarioBasedeDatos getInstance() {
		return instance;
	}

	public void setInstance(UsuarioBasedeDatos instance) {
		this.instance = instance;
	}
}
