package es.upm.fis2018.gm11_6.core;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : GM21 6
//  @ File Name : UsuarioMiembro.java
//  @ Date : 23/05/2018
//  @ Author :
//
//

//IMPORTS JAVA
import java.util.Date;
import java.util.ArrayList;
// ------***------



public class Usuario {
	
	private String nombre;
	private String apellidos;
	private String alias;
	private String correoUPM;
	private String password;
	private String agendaFavorita = " ";;	
	private int idUsuario;	
	private Date date = new Date ();
	private Perfil perfilUsuario;
	private ArrayList<Mensaje> mensajesUsuario;
	private ArrayList<Agenda> agendasUsuario;
	private ArrayList<Conversacion> conversacionesPart; //conversaciones en las que participa
	
	
	public Usuario(String nombre, String apellidos, String alias, String correo, String pass, int id) {
		this.nombre 	= nombre;
		this.apellidos 	= apellidos;
		this.alias 		= alias;
		this.correoUPM 	= correo;
		this.password 	= pass;
		this.idUsuario 	= id;
		this.perfilUsuario 		= new Perfil(); // crea automaticamente el perfil
		this.mensajesUsuario 	= new ArrayList<Mensaje> (); // Mejor usar un array list que un array clasico
		this.agendasUsuario  	= new ArrayList<Agenda> ();
		this.agendasUsuario.add(new Agenda("default"));
		this.conversacionesPart = new ArrayList<Conversacion>();
		
	}
	
	//Coge un correo y una pass y comprueba si esta bien escrita
	public boolean verificarLogin (String correo, String pass) {
		if (correo.equals(this.correoUPM)) {
			if (pass.equals(this.password)){
				return true;
			} else {
				System.out.println("password incorrecta");
				return false;
			}
		} else {
			System.out.println("correo incorrecto");
			return false;
		}
		// revisar, debe obtener toda la lista de correos y una vez encontrado, comprobar contraseña 
	}
	
	public Agenda buscarAgendaPorNombre (String nombreAgenda){
		for(int i = 0; i < this.agendasUsuario.size(); i++) {
			if (this.agendasUsuario.get(i).getNombre().equals(nombreAgenda)) {
				return this.agendasUsuario.get(i);
			} 
		} 
		return null;
	}
	
	public void anyadirAgenda (Agenda agenda) {
		this.agendasUsuario.add(agenda);
	}
	public void anyadirAgenda (String nombre) {
		this.agendasUsuario.add(new Agenda(nombre));
	}

	public Boolean confirmar(Usuario usuario) {
		return true;
	}

	public String mostrarDatos() {
		return getIdUsuario() + "\t" + getNombre() + "\t" + getApellidos() + "\t" + getAlias() + "\t"
			     + getCorreoUPM();
	}

	//CONVERSACIONES
	public void anyadirConversacion (Conversacion conv) {
		this.conversacionesPart.add(conv);
	}
	// muestra las conversaciones que el usuario tiene iniciadas
	public void mostrarConversaciones() {
		System.out.println("Conversaciones activas");		
		for (int i = 0; i < this.conversacionesPart.size(); i++) {
			if (this.conversacionesPart.get(i).getReceptor().equals(this)) {
				System.out.println("[" + this.conversacionesPart.get(i).getIdConversacion() + "]: Conversacion con '" + this.conversacionesPart.get(i).getEmisor().getCorreoUPM() + "' --Mensajes: " + this.conversacionesPart.get(i).getListaMensajes().size());
			}
			else System.out.println("[" + this.conversacionesPart.get(i).getIdConversacion() + "]: Conversacion con '" + this.conversacionesPart.get(i).getReceptor().getCorreoUPM() + "' --Mensajes: " + this.conversacionesPart.get(i).getListaMensajes().size());
		}		
	}
	//comprueba que pertenece a la conversacion
	public boolean entrarConversacion(Conversacion conv) {
		if (conv.getEmisor().equals(this) || conv.getReceptor().equals(this)) {
			return true;
		} else return false;
	}
	
	public Date getCreationDate ()
    {
        return date;
    }
	// SETTERS AND GETTERS
	public String getNombre() {
		return nombre;
	}
	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	public String getApellidos() {
		return apellidos;
	}
	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}
	public String getAlias() {
		return alias;
	}
	public void setAlias(String alias) {
		this.alias = alias;
	}
	public String getCorreoUPM() {
		return correoUPM;
	}
	public void setCorreoUPM(String correoUPM) {
		this.correoUPM = correoUPM;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getAgendaFavorita() {
		return agendaFavorita;
	}
	public void setAgendaFavorita(String agendaFavorita) {
		this.agendaFavorita = agendaFavorita;
	}
	public int getIdUsuario() {
		return idUsuario;
	}
	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}
	public ArrayList<Mensaje> getMensajesUsuario() {
		return mensajesUsuario;
	}
	public void setMensajesUsuario(ArrayList<Mensaje> mensajesUsuario) {
		this.mensajesUsuario = mensajesUsuario;
	}
	public Perfil getPerfilUsuario() {
		return perfilUsuario;
	}
	public void setPerfilUsuario(Perfil perfilUsuario) {
		this.perfilUsuario = perfilUsuario;
	}
	
	public void setAgendasUsuario(ArrayList<Agenda> agendasUsuario) {
		this.agendasUsuario = agendasUsuario;
	}
	public ArrayList<Agenda> getAgendasUsuario() {
		return agendasUsuario;
	}

	public ArrayList<Conversacion> getConversacionesPart() {
		return conversacionesPart;
	}
	public void setConversacionesPart(ArrayList<Conversacion> conversacionesPart) {
		this.conversacionesPart = conversacionesPart;
	}	
	
}
